### ISSUE TITLE
Feature: support for unnamed imports

### ISSUE THREAD

**Issue by saravanabalagi** [jimkyndemeyer/react-css-modules-intellij-plugin#10]
Currently syntax highlighting happens only if I require a .css file.

```jsx
import './welcome.scss';                            // does NOT work
import styles from './welcome.scss';                // works
require './welcome.scss';                           // works

<View styleName="container">
```

```css
.container {
  flex: 1;
  justify-content: center;
  align-items: center;
  background-color: #333;
}
```
